-- MySQL Script generated by MySQL Workbench
-- Sun Mar 19 05:28:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pizzeria` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `mydb`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Provincia` (
  `id_provincia` INT NOT NULL,
  `nombre_provincia` VARCHAR(45) NULL,
  PRIMARY KEY (`id_provincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Localidad` (
  `id_localidad` INT NOT NULL,
  `nombre_localidad` VARCHAR(45) NULL,
  `id_provincia` INT NOT NULL,
  PRIMARY KEY (`id_localidad`),
  INDEX `fk_Localidad_Provincia_idx` (`id_provincia` ASC) ,
  CONSTRAINT `fk_Localidad_Provincia`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `pizzeria`.`Provincia` (`id_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Cliente` (
  `id_cliente` INT NOT NULL,
  `nombre_cliente` VARCHAR(45) NULL,
  `apellido_cliente` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(45) NULL,
  `telefono` VARCHAR(9) NULL,
  `id_localidad` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_Cliente_Localidad1_idx` (`id_localidad` ASC) ,
  CONSTRAINT `fk_Cliente_Localidad1`
    FOREIGN KEY (`id_localidad`)
    REFERENCES `pizzeria`.`Localidad` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Tienda` (
  `id_tienda` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `codigo_postal` VARCHAR(45) NULL,
  `id_localidad` INT NOT NULL,
  PRIMARY KEY (`id_tienda`),
  INDEX `fk_Tienda_Localidad1_idx` (`id_localidad` ASC) ,
  CONSTRAINT `fk_Tienda_Localidad1`
    FOREIGN KEY (`id_localidad`)
    REFERENCES `pizzeria`.`Localidad` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Empleado` (
  `id_empleado` INT NOT NULL,
  `nombre_empleado` VARCHAR(45) NULL,
  `apellido_empleado` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NULL,
  `telefono` VARCHAR(9) NULL,
  `tipo_empleado` ENUM('cocinero', 'repartidor') NULL,
  `id_tienda` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_Empleado_Tienda1_idx` (`id_tienda` ASC) ,
  CONSTRAINT `fk_Empleado_Tienda1`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `pizzeria`.`Tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Pedido` (
  `id_pedidos` INT NOT NULL,
  `fecha_hora` DATETIME NULL,
  `tipo_pedido` ENUM('domicilio', 'recojo') NULL,
  `precio_total` DOUBLE NULL,
  `id_cliente` INT NOT NULL,
  `id_tienda` INT NOT NULL,
  `id_empleado` INT NULL,
  `fecha_hora_entrega` DATETIME NULL,
  PRIMARY KEY (`id_pedidos`),
  INDEX `fk_Pedidos_Cliente1_idx` (`id_cliente` ASC) ,
  INDEX `fk_Pedidos_Tienda1_idx` (`id_tienda` ASC) ,
  INDEX `fk_Pedidos_Empleado1_idx` (`id_empleado` ASC) ,
  CONSTRAINT `fk_Pedidos_Cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `pizzeria`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Tienda1`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `pizzeria`.`Tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `pizzeria`.`Empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Categoria_pizza` (
  `id_categoria_pizza` INT NOT NULL,
  `nombre_categoria` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria_pizza`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Producto` (
  `id_producto` INT NOT NULL,
  `categoria_producto` ENUM('bebida','hamburguesa','pizza') NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `descripcion_producto` TEXT NULL,
  `imagen_producto` VARCHAR(45) NOT NULL,
  `precio_producto` DOUBLE NOT NULL,
  `id_categoria_pizza` INT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_Producto_Categoria_pizza1_idx` (`id_categoria_pizza` ASC) ,
  CONSTRAINT `fk_Producto_Categoria_pizza1`
    FOREIGN KEY (`id_categoria_pizza`)
    REFERENCES `pizzeria`.`Categoria_pizza` (`id_categoria_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Pedido_has_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Pedido_has_Producto` (
  `Pedido_id_pedidos` INT NOT NULL,
  `Producto_id_producto` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`Pedido_id_pedidos`, `Producto_id_producto`),
  INDEX `fk_Pedido_has_Producto_Producto1_idx` (`Producto_id_producto` ASC) ,
  INDEX `fk_Pedido_has_Producto_Pedido1_idx` (`Pedido_id_pedidos` ASC) ,
  CONSTRAINT `fk_Pedido_has_Producto_Pedido1`
    FOREIGN KEY (`Pedido_id_pedidos`)
    REFERENCES `pizzeria`.`Pedido` (`id_pedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Producto_Producto1`
    FOREIGN KEY (`Producto_id_producto`)
    REFERENCES `pizzeria`.`Producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

